server:
  port: 9089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    cloud:
      openfeign:
        circuitbreaker:
          enabled: true


logging:
  level:
    root: INFO


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 5000

retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 10s





